### ISSUE TITLE
ImportError: cannot import name 'factorial' from 'scipy.misc'

### ISSUE THREAD

**Issue by Cyberface** [llondon6/positive#24]
When trying to import positive I get

```
ImportError: cannot import name 'factorial' from 'scipy.misc'
```

Googling I found this: 

https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial

I think you need to change

`from scipy.misc import factorial` to `from scipy.special import factorial`

**Comment by llondon6** [comment]
Thanks! I've fixed it in this commit: https://github.com/llondon6/positive/commit/ed2ff1914d07a1c6e6019e01d22c3c04f3da6df0

And I've started fixing all of the print commands -- I finally started using python3 last week :-)

**Comment by llondon6** [comment]
Ok, as of [this commit](https://github.com/llondon6/positive/commit/15841c1c4c74fa09a6dbb870c01ac85bb2808278) you should be able to import and use with python 3.6

**Comment by llondon6** [comment]
in case you've installed using pip, the latest release now has these changes as well

**Comment by Cyberface** [comment]
I did install via pip! Thanks!

**Comment by llondon6** [comment]
hmm, I'm not sure if pip -U pulls pre-release versions so I've made a minor change to the latest release, so maybe try again now if it didn't work the first time

**Comment by llondon6** [comment]
and sorry I also need to update the setup.py one moment ....

**Comment by llondon6** [comment]
@Galadirith do you happen to know how pip handles this? does it take a day or so to notice new releases? I've not been able to 

`pip install positive==0..2.2`

**Comment by Galadirith** [comment]
@llondon6 @Cyberface Sorry about not having the latest version on PyPI. That actually isn't an automated process (I never set up any CI to package when the repo is tagged 😅). You have to manually package `positive` and then push to PyPI. I always package with docker just because it is easier, here are the scripts I use.

`bin/package.sh`

```
#!/usr/bin/env bash

mkdir -p dist
docker run \
--rm \
-it \
-v ${PWD}/bin:/root/bin \
-v ${PWD}/dist:/root/dist \
-v ${HOME}/projects/positive:/root/src/positive \
-w /root/src/positive \
-e TWINE_USERNAME=Galadirith \
-e TWINE_PASSWORD=**************** \
python:3 \
/root/bin/_package.sh
```

`bin/_package.sh`

```
#!/usr/bin/env bash

pip install --upgrade setuptools wheel
pip install twine
python setup.py sdist -d /root/dist/ bdist_wheel -d /root/dist/ --universal
# twine upload --repository-url https://test.pypi.org/legacy/ /root/dist/*
twine upload /root/dist/*
```

Then just run `./bin/package.sh`. You need to create an account on PyPI to be able to upload, and then I can add you as owner of the [`positive` package](https://pypi.org/project/positive/) on PyPI :blush:

I always run a test to test.pypi.org first as well just to make sure everything packages properly. If you create an account on there as well (pypi.org and test.pypi.org have separate accounts) I can add you as an owner to the [`positive` package there](https://test.pypi.org/project/positive/) as well :blush: You can push to the test site by swapping the commented line on `bin/_package.sh` with the last (uncommented) line.

This packaged fine to test.pypi.org but it's failing to `import` correctly under 2.7 because of 

https://github.com/llondon6/positive/blob/92fa1fc31faaa8a4b8a5b121a3bba1149a43fedc/positive/physics.py#L3711

I think that this should be a simple fix with a merge from #25 and then I can build again and publish to PyPI 👍 😊

**Comment by Galadirith** [comment]
Everything is working for Python 2.7+3.7 from https://test.pypi.org/project/positive/ so I'll push to pypi.org now 😊 should be uploaded in ~10mins 👍

**Comment by Galadirith** [comment]
@llondon6 @Cyberface `positive@0.2.3` is now [published to PyPi](https://pypi.org/project/positive/0.2.3/) so you should be able to pip install as normal 👍

**Comment by llondon6** [comment]
awesome :D thanks so much, Ed!

On Nov 26, 2019, at 5:30 PM, Edward Fauchon-Jones <notifications@github.com> wrote:

@llondon6 <https://github.com/llondon6> @Cyberface <https://github.com/Cyberface> positive@0.2.3 is now published to PyPi <https://pypi.org/project/positive/0.2.3/> so you should be able to pip install as normal 👍
